apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  labels:
    app: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          # Replace with your container registry and version tag
          image: account-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              value: p@ssw0rd
            - name: SECRET_KEY
              value: superSecretKey
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  type: ClusterIP
  selector:
    app: account-service
  ports:
    - port: 8081
      targetPort: 8081